# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Introduction
    url: introduction/
    weight: 10

  - name: Studying
    url: studying/
    weight: 20
  - name: Experience
    url: experience/
    weight: 30
  - name: Projects
    url: projects/
    weight: 40
  - name: Contact
    identifier: contact
    url: contact/
    weight: 50
  - name: Contact Information
    parent: contact
    url: contact/contact/
    weight: 51
  - name: Map
    parent: contact
    url: contact/map/
    weight: 52